# Generated by Django 5.1 on 2024-09-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lobby',
            name='players',
        ),
        migrations.AddField(
            model_name='lobby',
            name='name',
            field=models.CharField(default='Lobby_default_name', max_length=255),
        ),
    ]
