# Generated by Django 5.1 on 2024-09-07 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_content_english_slang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='formal_version',
            field=models.CharField(max_length=1024),
        ),
    ]
