# Generated by Django 5.1 on 2024-09-07 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_content_formal_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='english_slang',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='content',
            name='formal_version',
            field=models.CharField(max_length=255),
        ),
    ]
