# Generated by Django 5.1 on 2024-09-13 05:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_score_user_score_player1_score_player2'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordslearned',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
