# Generated by Django 5.1 on 2024-09-13 11:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('api', '0005_wordslearned_user_content'), ('api', '0006_alter_gamename_id'), ('api', '0007_wordslearned_seen_times'), ('api', '0008_alter_wordslearned_seen_times'), ('api', '0009_remove_wordslearned_user_content'), ('api', '0010_wordslearned_user_content'), ('api', '0011_remove_wordslearned_user_content')]

    dependencies = [
        ('api', '0004_wordslearned_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='wordslearned',
            constraint=models.UniqueConstraint(fields=('user', 'content'), name='user-content'),
        ),
        migrations.AlterField(
            model_name='gamename',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='wordslearned',
            name='seen_times',
            field=models.IntegerField(default=1),
        ),
        migrations.RemoveConstraint(
            model_name='wordslearned',
            name='user-content',
        ),
    ]
