# Generated by Django 5.1 on 2024-09-13 08:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_wordslearned_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='wordslearned',
            constraint=models.UniqueConstraint(fields=('user', 'content'), name='user-content'),
        ),
    ]
