# Generated by Django 5.1 on 2024-09-13 11:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_wordslearned_created_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="wordslearned",
            constraint=models.UniqueConstraint(fields=("user", "content"), name="user-content"),
        ),
        migrations.AlterField(
            model_name="gamename",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddField(
            model_name="wordslearned",
            name="seen_times",
            field=models.IntegerField(default=1),
        ),
        migrations.RemoveConstraint(
            model_name="wordslearned",
            name="user-content",
        ),
    ]
