# Generated by Django 5.1 on 2024-09-09 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_content_english_slang_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='english_slang',
            field=models.CharField(max_length=255),
        ),
    ]
