# Generated by Django 5.1 on 2024-09-14 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_wordslearned_user_content_squashed_0011_remove_wordslearned_user_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='game_id',
        ),
    ]
