# Generated by Django 5.1 on 2024-09-14 03:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_remove_score_game_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="score",
            old_name="player1",
            new_name="winner",
        ),
        migrations.RenameField(
            model_name="score",
            old_name="player2",
            new_name="loser",
        ),
    ]
