# Generated by Django 5.1 on 2024-09-01 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordslearned',
            name='content',
        ),
        migrations.RemoveField(
            model_name='lobby',
            name='game_type',
        ),
        migrations.RemoveField(
            model_name='lobby',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='lobby',
            name='players',
        ),
        migrations.RemoveField(
            model_name='score',
            name='game_id',
        ),
        migrations.RemoveField(
            model_name='score',
            name='user',
        ),
        migrations.RemoveField(
            model_name='wordslearned',
            name='user',
        ),
        migrations.DeleteModel(
            name='Content',
        ),
        migrations.DeleteModel(
            name='GameName',
        ),
        migrations.DeleteModel(
            name='Lobby',
        ),
        migrations.DeleteModel(
            name='Score',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='WordsLearned',
        ),
    ]
