services:
  db:
    container_name: db
    image: postgres:16-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./data/db:/var/lib/postgresql/data/
    networks:
      custom_network:
        aliases:
          - ${PROJECT_NAME}_db.local
  frontend:
    container_name: frontend
    build:
      context: ../nihongo-jouzu-frontend
      dockerfile: Dockerfile
      target: dev
    restart: always
    command: npm run dev
    env_file:
      - path: ../nihongo-jouzu-frontend/.env
        required: true
    environment:
      - NODE_ENV=development 
      #if you’re using Windows, you may need to uncomment the next line - Sol from @Kobe E
      - WATCHPACK_POLLING=true
    ports:
      - '3000:3000'
    volumes:
      - ../nihongo-jouzu-frontend:/app
      - ../nihongo-jouzu-frontend/node_modules:/app/node_modules
      - /app/.next
    depends_on:
      - backend
    networks:
      custom_network:
        aliases:
          - ${PROJECT_NAME}_react.local
  backend: 
    container_name: backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - PGPASSWORD=${PGPASSWORD}
      - PGUSER=${PGUSER}
      - POSTGRES_DB=${POSTGRES_DB}
      - DATABASE_HOST=db
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
      
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/app/backend
      - ./static:/app/backend/static
    depends_on:
      - db
    networks:
      custom_network:
        aliases:
          - ${PROJECT_NAME}_django.local
networks:
  custom_network:
    name: ${PROJECT_NAME}
    driver: bridge

volumes:
  node_modules:
    driver: local