[build]
builder  = "DOCKERFILE"
dockerfilePath = "./backend/Dockerfile"
rootDirectory = "./backend"
watchPatterns = [
    "requirements.txt", 
    "src/**", 
    "railway.toml",
    "Dockerfile",
]

[deploy]
runtime: "V2",
sleepApplication: true
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5