[build]
builder  = "DOCKERFILE"
dockerfilePath = "./backend/Dockerfile"
rootDirectory = "./backend"
watchPatterns = [
    "requirements.txt", 
    "backend/**", 
    "railway.toml",
    "Dockerfile",
]

[deploy]
runtime = "V2"
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
